### ISSUE TITLE
Version 1.0.0 causes downstream breakages (pry-rails)

### ISSUE THREAD

**Issue by jhsu802701** [banister/method_source#65] opened 2020-03-19 23:22 UTC
Running the "rails generate" command when pry-rails is installed leads to the error "undefined method `create_command' for #<Pry::CommandSet:0x00000000057ccb08>".  The "rails generate" command works if pry-rails is not installed.

The pry-rails gem was last updated on December 30, 2018.  The pry gem (dependency of pry-rails) was last updated on November 12, 2018.  The coderay gem (dependency of pry) was last updated on September 3, 2017.

The Gemfile.lock file shows that version 1.0.0 (latest one) of the method_source gem is in use.  This version of the gem was published today, March 19, 2020.

**Comment by kyrylo** [comment] 2020-03-20 11:10
* Are you on `pry master` or latest release?
* How's this issue connected to `method_source`?
* If you install latest Pry release, then `method_source` v1.0.0 *shouldn't* be installed due to a version requirement of `~> 0.9`

**Comment by jhsu802701** [comment] 2020-03-22 19:06
I use the latest releases of the pry and pry-rails gems.  Not pinning the method_source gem (which means using version 1.0.0) led to the error I cited.  I was able to resolve the problem by pinning method_source to version 0.9.2.

**Comment by kyrylo** [comment] 2020-03-28 14:48
I cannot reproduce this. I created a new Rails 6 app, added `pry-rails` as a dependency and generated a new model. It worked without any errors.

I am going to close the issue because there's no repro case and I don't see how `method_source` is connected to the issue. We didn't make any changes to Pry commands in this gem.

**Closed by kyrylo** 2020-03-28 14:48 UTC

**Comment by jhsu802701** [comment] 2020-03-28 17:50
I encountered this issue when creating a Rails 5.2 app.  I know that Rails 6 is current, but I have to rely on 5.2 until I get through the latest Rails Tutorial.
